# Use the README file as a reference to customize settings.

Category:
  fields:
    default: name, travel_mode, issue, icon_url
    form: name, travel_mode, issue, icon_url
  relationships: demands, users
  application: Tabelas 
