# Use the README file as a reference to customize settings.

Demand:
  fields:
    default: fullname, user_id, category_id
    form: fullname, user_id, category_id
  relationships: pins
  application: Tabelas 
